In [97]:
!pip install gdown

Requirement already satisfied: gdown in c:\users\pr00316649\appdata\local\programs\python\python314\lib\site-packages (6.1.0)
Requirement already satisfied: beautifulsoup4 in c:\users\pr00316649\appdata\local\programs\python\python314\lib\site-packages (from gdown) (4.15.0)
Requirement already satisfied: filelock in c:\users\pr00316649\appdata\local\programs\python\python314\lib\site-packages (from gdown) (3.32.5)
Requirement already satisfied: requests[socks] in c:\users\pr00316649\appdata\local\programs\python\python314\lib\site-packages (from gdown) (2.34.2)
Requirement already satisfied: tqdm in c:\users\pr00316649\appdata\local\programs\python\python314\lib\site-packages (from gdown) (4.70.0)
Requirement already satisfied: soupsieve>=1.6.1 in c:\users\pr00316649\appdata\local\programs\python\python314\lib\site-packages (from beautifulsoup4->gdown) (2.9.2)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\pr00316649\appdata\local\programs\python\python314\lib\site-packages (from beautifulsoup4->gdown) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\pr00316649\appdata\local\programs\python\python314\lib\site-packages (from requests[socks]->gdown) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\pr00316649\appdata\local\programs\python\python314\lib\site-packages (from requests[socks]->gdown) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\pr00316649\appdata\local\programs\python\python314\lib\site-packages (from requests[socks]->gdown) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\pr00316649\appdata\local\programs\python\python314\lib\site-packages (from requests[socks]->gdown) (2026.6.17)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in c:\users\pr00316649\appdata\local\programs\python\python314\lib\site-packages (from requests[socks]->gdown) (1.7.1)
Requirement already satisfied: colorama in c:\users\pr00316649\appdata\roaming\python\python314\site-packages (from tqdm->gdown) (0.4.6)

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [98]:
import pandas as pd

In [99]:
url = "https://docs.google.com/spreadsheets/d/1mYKc9swuEFi3OKnZtsNHy03cYFaYO3ELgKKd6XxVGDQ/edit?usp=sharing"

url

'https://docs.google.com/spreadsheets/d/1mYKc9swuEFi3OKnZtsNHy03cYFaYO3ELgKKd6XxVGDQ/edit?usp=sharing'

In [100]:
sheet_id = url.split("/d/")[1].split("/")[0]

csv_url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv"

csv_url

'https://docs.google.com/spreadsheets/d/1mYKc9swuEFi3OKnZtsNHy03cYFaYO3ELgKKd6XxVGDQ/export?format=csv'

In [101]:
df = pd.read_csv(csv_url)

df

,Processo,Documento,Resultado de referência,Resultado da ferramenta,Concordância,Unnamed: 5
0,1. SEI_60.016754_2026_14,Documento principal,Presente,Presente,SIM,NaN
1,1. SEI_60.016754_2026_14,Comprovante de endereço,Presente,Presente,SIM,NaN
2,1. SEI_60.016754_2026_14,Contrato Social ou CCMEI,Presente,Presente,SIM,NaN
3,1. SEI_60.016754_2026_14,CNPJ,Presente,Presente,SIM,NaN
4,1. SEI_60.016754_2026_14,RG/CPF ou Documento com foto,Ausente,Ausente,SIM,NaN
...,...,...,...,...,...,...
130,28. SEI_60.021726_2026_19 F,Documento principal,Presente,Presente,SIM,NaN
131,28. SEI_60.021726_2026_19 F,Comprovante de endereço,Presente,Ausente,NÃO,NaN
132,28. SEI_60.021726_2026_19 F,Contrato Social ou CCMEI,Presente,Ausente,NÃO,NaN
133,28. SEI_60.021726_2026_19 F,CNPJ,Ausente,Ausente,SIM,NaN
134,28. SEI_60.021726_2026_19 F,RG/CPF ou Documento com foto,Ausente,Ausente,SIM,NaN

In [102]:
df.columns

Index(['Processo', 'Documento', 'Resultado de referência',
       'Resultado da ferramenta', 'Concordância', 'Unnamed: 5'],
      dtype='str')

In [103]:
df.head()

,Processo,Documento,Resultado de referência,Resultado da ferramenta,Concordância,Unnamed: 5
0,1. SEI_60.016754_2026_14,Documento principal,Presente,Presente,SIM,NaN
1,1. SEI_60.016754_2026_14,Comprovante de endereço,Presente,Presente,SIM,NaN
2,1. SEI_60.016754_2026_14,Contrato Social ou CCMEI,Presente,Presente,SIM,NaN
3,1. SEI_60.016754_2026_14,CNPJ,Presente,Presente,SIM,NaN
4,1. SEI_60.016754_2026_14,RG/CPF ou Documento com foto,Ausente,Ausente,SIM,NaN

In [104]:
print(f"Quantidade de registros: {len(df)}")
print(f"Quantidade de colunas: {len(df.columns)}")

Quantidade de registros: 135
Quantidade de colunas: 6

In [105]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 135 entries, 0 to 134
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Processo                 135 non-null    str
 1   Documento                135 non-null    str
 2   Resultado de referência  135 non-null    str
 3   Resultado da ferramenta  135 non-null    str
 4   Concordância             135 non-null    str
 5   Unnamed: 5               1 non-null      str
dtypes: str(6)
memory usage: 15.0 KB

In [106]:
df.isna().sum()

Processo                     0
Documento                    0
Resultado de referência      0
Resultado da ferramenta      0
Concordância                 0
Unnamed: 5                 134
dtype: int64

In [107]:
print(f"Quantidade de registros: {len(df)}")
print(f"Quantidade de colunas: {len(df.columns)}")

df.info()

Quantidade de registros: 135
Quantidade de colunas: 6
<class 'pandas.DataFrame'>
RangeIndex: 135 entries, 0 to 134
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Processo                 135 non-null    str
 1   Documento                135 non-null    str
 2   Resultado de referência  135 non-null    str
 3   Resultado da ferramenta  135 non-null    str
 4   Concordância             135 non-null    str
 5   Unnamed: 5               1 non-null      str
dtypes: str(6)
memory usage: 15.0 KB

In [108]:
print(f"Registros duplicados: {df.duplicated().sum()}")

Registros duplicados: 0

## Matriz de confusão

Para avaliar o desempenho da ferramenta na **identificação da presença ou ausência dos documentos**, os resultados produzidos pela ferramenta são comparados aos resultados de referência, considerados como o resultado correto para a avaliação.

A **matriz de confusão** permite organizar os resultados dessa comparação em quatro categorias:

- **Verdadeiro Positivo (VP):** o documento está **Presente** segundo a referência e a ferramenta também o identifica como **Presente**.
- **Verdadeiro Negativo (VN):** o documento está **Ausente** segundo a referência e a ferramenta também o identifica como **Ausente**.
- **Falso Positivo (FP):** o documento está **Ausente** segundo a referência, mas a ferramenta o identifica como **Presente**.
- **Falso Negativo (FN):** o documento está **Presente** segundo a referência, mas a ferramenta o identifica como **Ausente**.

Nesta avaliação, **"Presente" é considerada a classe positiva**, enquanto **"Ausente" é considerada a classe negativa**.

A partir dessas quatro categorias, são calculadas as métricas de desempenho da ferramenta, como **acurácia, sensibilidade, especificidade, precisão e F1-score**.

Os valores de VP, VN, FP e FN são obtidos diretamente dos dados da planilha, de forma automática, para que os resultados sejam atualizados caso a base seja modificada.

In [109]:
pd.crosstab(
    df["Resultado de referência"],
    df["Resultado da ferramenta"],
    margins=True
)

Resultado da ferramenta  Ausente  Presente  All
Resultado de referência
Ausente                       29         4   33
Presente                       4        98  102
All                           33       102  135

In [110]:
vp = ((df["Resultado de referência"] == "Presente") & 
      (df["Resultado da ferramenta"] == "Presente")).sum()

vn = ((df["Resultado de referência"] == "Ausente") & 
      (df["Resultado da ferramenta"] == "Ausente")).sum()

fp = ((df["Resultado de referência"] == "Ausente") & 
      (df["Resultado da ferramenta"] == "Presente")).sum()

fn = ((df["Resultado de referência"] == "Presente") & 
      (df["Resultado da ferramenta"] == "Ausente")).sum()

print(f"Verdadeiros Positivos (VP): {vp}")
print(f"Verdadeiros Negativos (VN): {vn}")
print(f"Falsos Positivos (FP): {fp}")
print(f"Falsos Negativos (FN): {fn}")

Verdadeiros Positivos (VP): 98
Verdadeiros Negativos (VN): 29
Falsos Positivos (FP): 4
Falsos Negativos (FN): 4

## Acurácia

A **acurácia** representa a proporção de identificações realizadas corretamente pela ferramenta em relação ao total de documentos avaliados.

Nesse caso, considera-se como acerto tanto quando a ferramenta identifica corretamente um documento como **Presente** quanto quando identifica corretamente um documento como **Ausente**.

A acurácia é calculada pela seguinte fórmula:

$$
\text{Acurácia} = \frac{VP + VN}{VP + VN + FP + FN}
$$

Em que:

- **VP** = Verdadeiros Positivos;
- **VN** = Verdadeiros Negativos;
- **FP** = Falsos Positivos;
- **FN** = Falsos Negativos.

Quanto mais próxima de 100% a acurácia estiver, maior é a proporção de identificações corretas realizadas pela ferramenta.

In [111]:
acuracia = (vp + vn) / (vp + vn + fp + fn)

print(f"Acurácia: {acuracia:.2%}")

Acurácia: 94.07%

## Sensibilidade

A **sensibilidade** mede a capacidade da ferramenta de identificar corretamente os documentos que estão **Presentes** no processo.

Em outras palavras, indica a proporção de documentos que estavam presentes segundo o resultado de referência e que também foram identificados como presentes pela ferramenta.

A sensibilidade é calculada pela seguinte fórmula:

$$
\text{Sensibilidade} = \frac{VP}{VP + FN}
$$

Em que:

- **VP** = Verdadeiros Positivos;
- **FN** = Falsos Negativos.

Uma sensibilidade elevada indica que a ferramenta apresenta menor probabilidade de **deixar de identificar documentos que estão presentes**.

In [112]:
sensibilidade = vp / (vp + fn)

print(f"Sensibilidade: {sensibilidade:.2%}")

Sensibilidade: 96.08%

## Especificidade

A **especificidade** mede a capacidade da ferramenta de identificar corretamente os documentos que estão **Ausentes** no processo.

Em outras palavras, indica a proporção de documentos que estavam ausentes segundo o resultado de referência e que também foram identificados como ausentes pela ferramenta.

A especificidade é calculada pela seguinte fórmula:

$$
\text{Especificidade} = \frac{VN}{VN + FP}
$$

Em que:

- **VN** = Verdadeiros Negativos;
- **FP** = Falsos Positivos.

Uma especificidade elevada indica que a ferramenta apresenta menor probabilidade de **indicar como presente um documento que, na realidade, está ausente**.

In [113]:
especificidade = vn / (vn + fp)

print(f"Especificidade: {especificidade:.2%}")

Especificidade: 87.88%

## Precisão

A **precisão** mede a proporção de identificações como **Presente** realizadas corretamente pela ferramenta.

Em outras palavras, indica, entre todos os documentos que a ferramenta identificou como presentes, quantos estavam realmente presentes segundo o resultado de referência.

A precisão é calculada pela seguinte fórmula:

$$
\text{Precisão} = \frac{VP}{VP + FP}
$$

Em que:

- **VP** = Verdadeiros Positivos;
- **FP** = Falsos Positivos.

Uma precisão elevada indica que, quando a ferramenta identifica um documento como **Presente**, há maior probabilidade de essa identificação estar correta.

In [114]:
precisao = vp / (vp + fp)

print(f"Precisão: {precisao:.2%}")

Precisão: 96.08%

## F1-score

O **F1-score** é uma medida que combina **precisão** e **sensibilidade** em um único indicador.

Ele é calculado por meio da média harmônica entre precisão e sensibilidade, atribuindo o mesmo peso às duas métricas.

A fórmula é:

$$
F1 = 2 \times \frac{\text{Precisão} \times \text{Sensibilidade}}
{\text{Precisão} + \text{Sensibilidade}}
$$

O F1-score varia de 0 a 1, podendo também ser apresentado em percentual. Quanto mais próximo de 100%, maior é o equilíbrio entre a capacidade da ferramenta de identificar corretamente os documentos presentes e a proporção de suas identificações positivas que estão corretas.

In [115]:
f1 = 2 * (precisao * sensibilidade) / (precisao + sensibilidade)

print(f"F1-score: {f1:.2%}")

F1-score: 96.08%

## Síntese das métricas de desempenho

As métricas calculadas são consolidadas a seguir para facilitar a visualização do desempenho da ferramenta na identificação da presença ou ausência dos documentos.

Os resultados são calculados automaticamente a partir dos dados da planilha e das classificações de Verdadeiros Positivos (VP), Verdadeiros Negativos (VN), Falsos Positivos (FP) e Falsos Negativos (FN).

In [116]:
metricas = pd.DataFrame({
    "Métrica": [
        "Acurácia",
        "Sensibilidade",
        "Especificidade",
        "Precisão",
        "F1-score"
    ],
    "Resultado": [
        acuracia,
        sensibilidade,
        especificidade,
        precisao,
        f1
    ]
})

metricas["Resultado"] = metricas["Resultado"].map(lambda x: f"{x:.2%}")

metricas

          Métrica Resultado
0        Acurácia    94.07%
1   Sensibilidade    96.08%
2  Especificidade    87.88%
3        Precisão    96.08%
4        F1-score    96.08%

In [117]:
import ollama

In [118]:
resultados = "\n".join(
    f"- {linha['Métrica']}: {linha['Resultado']}"
    for _, linha in metricas.iterrows()
)

print(resultados)

- Acurácia: 94.07%
- Sensibilidade: 96.08%
- Especificidade: 87.88%
- Precisão: 96.08%
- F1-score: 96.08%

In [119]:
resposta = ollama.chat(
    model="llama3.2:3b",
    messages=[
        {
            "role": "user",
            "content": f"""
Analise de forma simples os resultados de desempenho de uma
ferramenta de identificação documental.

As métricas calculadas foram:

{resultados}

Explique:
1. O que os resultados indicam sobre o desempenho geral da ferramenta;
2. Qual métrica apresentou o melhor resultado;
3. Qual métrica apresentou o menor resultado;
4. Se há algum ponto de atenção.

Responda em português, de forma objetiva, em no máximo 2 parágrafos.
Não faça novos cálculos e não invente informações que não estejam nos dados.
"""
        }
    ]
)

from IPython.display import Markdown, display

display(Markdown(resposta["message"]["content"]))

Os resultados apresentados indicam que a ferramenta de identificação documental apresentou um desempenho geral satisfatório, com uma combinação de métricas que sugerem uma boa capacidade de identificação de documentos. A acurácia, sensibilidade e precisão são todas próximas e altas, com valores que superam os 90% e 96%, respectivamente. Isso indica que a ferramenta é capaz de identificar de forma precisa a grande maioria dos documentos. Já a especificidade, embora alta, está ligeiramente abaixo dos 90%, o que pode indicar uma minoridade de falsos positivos.

A métrica que apresentou o melhor resultado é a sensibilidade, que é de 96.08%, indicando que a ferramenta é capaz de detectar a maioria dos documentos corretamente. Já a especificidade apresentou o menor resultado, com um valor de 87.88%, o que pode indicar uma minoridade de falsos positivos. Por outro lado, a precisão e a F1-score também são altas e próximas, o que sugere que a ferramenta é capaz de identificar de forma precisa a maioria dos documentos.